#!/bin/bash -e

if [ ${EUID} -ne 0 ]; then
  echo "ERROR: This installation script must be run as root."
  exit 1
fi

sv stop koruza-nodewatcher koruza-gpio koruza-webui koruza-sensors koruza-spiral-scan 2>/dev/null || true
/koruza/install-packages
/koruza/install-config
sv start koruza-nodewatcher koruza-gpio koruza-webui koruza-sensors koruza-spiral-scan
