#!/bin/bash -e

if [ ${EUID} -ne 0 ]; then
  echo "ERROR: This installation script must be run as root."
  exit 1
fi

SERVICES="koruza-nodewatcher koruza-gpio koruza-webui koruza-sensors koruza-spiral-scan koruza-webcam koruza-vpn"

sv -v stop ${SERVICES} 2>/dev/null || true
/koruza/install-packages
/koruza/install-config
sv -v start ${SERVICES}
