#!/bin/bash -e

if [ ${EUID} -ne 0 ]; then
  echo "ERROR: This installation script must be run as root."
  exit 1
fi

UPGRADE_PACKAGE="$1"
if [ -z "${UPGRADE_PACKAGE}" ]; then
  echo "ERROR: Missing path to upgrade package."
  exit 1
fi

# Do not shutdown the reverse-ssh service as otherwise we may lose connectivity.
UPGRADE_SERVICES="koruza-nodewatcher koruza-gpio koruza-webui koruza-sensors koruza-spiral-scan"

update-rc.d watchdog remove
/etc/init.d/watchdog stop
sv stop ${UPGRADE_SERVICES}

tar -xf ${UPGRADE_PACKAGE} -C /

/koruza/install-packages
/koruza/install-config

sv start ${UPGRADE_SERVICES}
