#!/bin/bash -e

if [ ${EUID} -ne 0 ]; then
  echo "ERROR: This installation script must be run as root."
  exit 1
fi

UPGRADE_PACKAGE="$1"
UPGRADE_DIR=/tmp/upgrade-koruza-repo
if [ -z "${UPGRADE_PACKAGE}" ]; then
  echo "No upgrade package specified, upgrading to latest master."
  rm -rf "${UPGRADE_DIR}"
  git clone https://github.com/IRNAS/koruza-pi "${UPGRADE_DIR}"
  cd "${UPGRADE_DIR}"
  ./make-package.sh
  UPGRADE_PACKAGE="${UPGRADE_DIR}/koruza-package.tar.bz2"
fi

# Do not shutdown the vpn service as otherwise we may lose connectivity.
UPGRADE_SERVICES="koruza-nodewatcher koruza-gpio koruza-webui koruza-sensors koruza-spiral-scan koruza-webcam"

update-rc.d watchdog remove
/etc/init.d/watchdog stop
sv -w 30 stop ${UPGRADE_SERVICES}

cp /koruza/config/koruza.conf /tmp/koruza.conf

tar -xf ${UPGRADE_PACKAGE} -C /

mv /tmp/koruza.conf /koruza/config/koruza.conf

/koruza/install-packages
/koruza/install-config

sv -w 30 start ${UPGRADE_SERVICES}

rm -rf "${UPGRADE_DIR}"
